### ISSUE TITLE
Deprecation in 3.7 due to collections interface change

### ISSUE THREAD

**Issue by shannonfenn** [kolypto/py-good#15]
In Python 3.7, importing directly from the collections module triggers warning which will error in the future. 

  .../lib/python3.7/site-packages/good/validators/values.py:41: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    assert isinstance(container, collections.Container), '`container` must support `in` operation'

**Comment by kolypto** [comment]
@shannonfenn , thank you for your vigilance! :)
