### ISSUE TITLE
Good pollutes builtins, does not work in REPLs

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [kolypto/py-good#18]
Good pollutes  `_` into the builtins namespace, both inside and outside IPython. I have seen this conflict cause issues like the ones reported in #3, #4 and #5 with the latest Python (3.7.3). Previous issues were closed after @kolypto suggested to upgrade IPython, but I am *not* using IPython. I don't think there is anything special with my environment.

I am using `good==0.0.7.post1`

```
$ python
Python 3.7.3 (default, Aug 27 2019, 22:19:41) 
[GCC 4.7.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> repr(_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_' is not defined
>>> 'test'
'test'
>>> repr(_)
"'test'"
>>> import builtins
>>> repr(builtins._)
'"\'test\'"'
>>> import good
>>> repr(builtins._)
'<bound method NullTranslations.gettext of <gettext.NullTranslations object at 0x7fa5b4fde7f0>>'
```

**Comment by DiegoAlbertoTorres** [comment]
Seems like good/__init__.py:24 uses `gettext.install`, which pollutes builtins as per the documentation: https://docs.python.org/3/library/gettext.html#gettext.install

**Comment by kolypto** [comment]
Hi @DiegoAlbertoTorres ,
I've just fixed it in the recent release :)
