### ISSUE TITLE
Incorrect error message for schemas with lists of dictionaries

### ISSUE THREAD

**Issue by wsong** [kolypto/py-good#7]
```
import good
HOST_SCHEMA = good.Schema({ "host": str, "port": int })
schema = good.Schema("hosts": [ HOST_SCHEMA ])
# Note that we specify a string instead of an int for "port"
schema({ "hosts": [ { "host": "example.com", "port": "22" } ] })
```

The above code raises:

```
good.schema.errors.Invalid: Invalid value @ ['hosts'][0]: expected List[Dictionary[port,host,*]], got {'port': '22', 'host': 'test.com'}
```

This error message is fairly confusing (it does not, for instance, note that "port" has an incorrect type) and is fairly misleading, if not outright incorrect; the value for ["hosts"][0] should be a dictionary, not a list of dictionaries.

**Comment by vartagg** [comment]
You has a syntax error in 
`schema = good.Schema("hosts": [ HOST_SCHEMA ])`

I transformed this to

`schema = good.Schema({"hosts": [ HOST_SCHEMA ]})`

So in latest version `good==0.0.7.post0` the output of your commands looks like this:

`Invalid: Wrong type @ ['hosts'][0]['port']: expected Integer number, got String`

It's very likely that now it is writing everything correctly.

**Comment by kolypto** [comment]
@vartagg is right: that' a synthax error. @wsong , please reopen the issue if this is still relevant
